#!/usr/bin/env bash
# Deploy configuration for rudraspirit.com (LocalWP -> Hostinger).
# Sourced by deploy.sh. Edit values here, not in deploy.sh.

# ---- Live server (Hostinger SSH) ----
SSH_HOST="217.21.74.44"
SSH_PORT="65002"
SSH_USER="u362580417"
SSH_KEY="/root/.ssh/hostinger_rudraspirit"   # generated by deploy.sh setup

# Live WordPress docroot. Set explicitly to avoid AUTO detecting other domain roots.
REMOTE_WP="/home/u362580417/domains/rudraspirit.com/public_html/app/public"

# ---- URLs (for DB search-replace) ----
LOCAL_URL="https://rudraspirit.local"
LIVE_URL="https://rudraspirit.com"
LOCAL_HOST="rudraspirit.local"
LIVE_HOST="rudraspirit.com"

# ---- Local DB (LocalWP MySQL) ----
LOCAL_DB_HOST="127.0.0.1"
LOCAL_DB_PORT="10012"
LOCAL_DB_NAME="local"
LOCAL_DB_USER="root"
LOCAL_DB_PASS="root"
MYSQLDUMP="/mnt/c/Users/gnand/AppData/Roaming/Local/lightning-services/mysql-8.4.0/bin/win64/bin/mysqldump.exe"

# ---- Local files ----
LOCAL_PUBLIC="$(cd "$(dirname "${BASH_SOURCE[0]}")/app/public" && pwd)"

# ---- What to sync (relative to wp-content) ----
# wp-config.php and core are never pushed. Hostinger plugins kept on server.
TAR_EXCLUDES=(
  "--exclude=cache"
  "--exclude=*.disabled"
  "--exclude=debug.log"
  "--exclude=*.log"
  "--exclude=advanced-cache.php"
  "--exclude=object-cache.php"
  "--exclude=db.php"
  "--exclude=upgrade"
  "--exclude=upgrade-temp-backup"
  "--exclude=.DS_Store"
)
